# Define base image, use prebuilt arch 80 nerfstudio image.
FROM toomy0toons/nerfstudio:arch80

# metainformation
#LABEL org.opencontainers.image.version = "0.1.18"
#LABEL org.opencontainers.image.source = "https://github.com/nerfstudio-project/nerfstudio"
#LABEL org.opencontainers.image.licenses = "Apache License 2.0"
#LABEL org.opencontainers.image.base.name="docker.io/library/nvidia/cuda:11.8.0-devel-ubuntu22.04"

# Switch to Nerfstudio user.
USER 1000
WORKDIR /home/user


# Copy current nerfstudio(sdfstudio) folder and give ownership to user.
ADD . /home/user/nerfstudio
USER root
RUN chown -R user /home/user/nerfstudio
USER 1000

# Install sdfstudio
RUN cd nerfstudio && \
    python3.10 -m pip install -e  . && \
    cd ..

# Change working directory
WORKDIR /workspace

# add /usr/bin to path, so that QT5 package can be found.
ENV PATH="/usr/bin:${PATH}"
SHELL ["/bin/bash", "-c"]

# Install nerfstudio cli auto completion and enter shell if no command was provided.
CMD ns-install-cli --mode install && /bin/bash